# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'jan-azure1(563641ea-4294-4002-aedc-b0a97aa107fe)'
    subscriptionId: '563641ea-4294-4002-aedc-b0a97aa107fe'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ms-challenge-rg'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/JanShalom/JanShalom.git'
    overrideParameters: '-projectName jantoms'
    deploymentMode: 'Incremental'
    deploymentName: 'MSDeployPipeline'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
