# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'MS Challenge connection'
    subscriptionId: '1bffb4f7-22b2-48fb-84f3-8b22cf09590f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'MS Challenge'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/JanShalom/JanShalom.git'
    overrideParameters: '-projectName [EnterAProjectName].'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
